from _ssl import CERT_REQUIRED, CERT_OPTIONAL, CERT_NONE
from ssl import _DEFAULT_CIPHERS


class StompSSLSpec(object):
    SSLv2 = 'SSLv2'
    SSLv23 = 'SSLv23'
    SSLv3 = 'SSLv3'
    TLSv1 = 'TLSv1'
    TLSv1_1 = 'TLSv1_1'
    TLSv1_2 = 'TLSv1_2'

    SSL_VERSIONS = {SSLv2, SSLv23, SSLv3, TLSv1, TLSv1_1, TLSv1_2}

    OP_CIPHER_SERVER_PREFERENCE = 'OP_CIPHER_SERVER_PREFERENCE'
    OP_NO_COMPRESSION = 'OP_NO_COMPRESSION'
    OP_NO_SSLv2 = 'OP_NO_SSLv2'
    OP_NO_SSLv3 = 'OP_NO_SSLv3'
    OP_NO_TLSv1 = 'OP_NO_TLSv1'
    OP_NO_TLSv1_1 = 'OP_NO_TLSv1_1'
    OP_NO_TLSv1_2 = 'OP_NO_TLSv1_2'
    OP_SINGLE_DH_USE = 'OP_SINGLE_DH_USE'
    OP_SINGLE_ECDH_USE = 'OP_SINGLE_ECDH_USE'

    SSL_OPTIONS = {
        OP_CIPHER_SERVER_PREFERENCE,
        OP_NO_COMPRESSION,
        OP_NO_SSLv2,
        OP_NO_SSLv3,
        OP_NO_TLSv1,
        OP_NO_TLSv1_1,
        OP_NO_TLSv1_2,
        OP_SINGLE_DH_USE,
        OP_SINGLE_ECDH_USE
    }

    DEFAULT_SSL_OPTIONS = [
        OP_NO_SSLv2,
        OP_NO_SSLv3,
        OP_NO_COMPRESSION,
        OP_CIPHER_SERVER_PREFERENCE,
        OP_SINGLE_DH_USE,
        OP_SINGLE_ECDH_USE
    ]

    DEFAULT_CIPHERS = _DEFAULT_CIPHERS

    CERT_REQUIRED = CERT_REQUIRED
    CERT_OPTIONAL = CERT_OPTIONAL
    CERT_NONE = CERT_NONE

    CERT_OPTIONS = {
        CERT_REQUIRED,
        CERT_OPTIONAL,
        CERT_NONE,
    }
